version: "3.8"

services:
  app:
    container_name: "application"
    build: ./project
    restart: always
    ports:
      - "${APPLICATION_PORT:-80}:8080"
    environment:
      WAIT_HOSTS: database:5432
    volumes:
      - "./project:/app"
    depends_on:
      - database
  database:
    container_name: "database"
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
